### ISSUE TITLE
【任务发布】user: 实现用户注册/登录/登出的接口

### ISSUE THREAD

**Issue by val213** [val213/Mail#10]

**Comment by val213** [comment]
用户注册登录的实现有3种方案：
- 一是使用redis，便于在需要服务器集群的场景下，服务器之间共享用户的登陆的会话状态，虽然有现成的项目代码可以参考，但由于我们项目周期比较短，应用场景比较有限，目前暂时不考虑？
- 二是使用cookies，用户未登录之前，http请求是不带cookie的，登录后，客户端会将登录信息放在请求中给服务端，服务端进行验证，登录成功后，服务端会把用户信息放在cookie里面，随着响应返回给客户端，客户端就会储存这个cookie。下次再访问网站，cookie会和客户端的请求一起发给服务端，服务端验证信息正确，判断这个用户是登录状态。
- 三是使用基于cookie的session，现在网站登录都使用session机制，它和cookie机制最大的区别就是用户信息不再放在客户端而是服务端，session的值是存在于每个tomcat服务器之中的。session以cookie作为载体，cookie里面只储存一个session id，与服务端通信。每个客户端每一次登录请求都会和服务端会生成唯一的session id，相当于客户端每次只要告诉服务端session id，服务端就可以找到相对应的客户端数据。


参考：
- [redis实现用户登录/注册](https://blog.csdn.net/Peaceuai/article/details/127943510)
- [手把手教你使用Spring Boot从零开始制作用户注册登录功能](https://developer.aliyun.com/article/1175982#:~:text=%E6%89%8B%E6%8A%8A%E6%89%8B%E6%95%99%E4%BD%A0%E4%BD%BF%E7%94%A8Spring%20Boot%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E5%88%B6%E4%BD%9C%E7%94%A8%E6%88%B7%E6%B3%A8%E5%86%8C%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD%201%201%EF%BC%8C%E5%9F%BA%E6%9C%AC%E7%9F%A5%E8%AF%86-%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E7%9A%84%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%90%86%20%E5%AF%B9%E4%BA%8E%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%EF%BC%8C%E6%88%91%E4%BB%AC%E4%B8%80%E5%AE%9A%E9%83%BD%E5%90%AC%E8%AF%B4%E8%BF%87%20cookie%20%E8%BF%99%E4%B8%AA%E8%AF%8D%E3%80%82%20%E5%85%B6%E5%AE%9E%EF%BC%8C,%EF%BC%8C%E5%AE%9E%E9%99%85%E6%A0%B9%E6%8D%AE%E4%B8%9A%E5%8A%A1%E9%9C%80%E8%A6%81%E4%B8%8D%E5%90%8C%EF%BC%8C%E7%94%A8%E6%88%B7%E7%B1%BB%E5%8F%AF%E8%83%BD%E6%9C%89%E5%BE%88%E5%A4%9A%E5%B1%9E%E6%80%A7%EF%BC%8C%E8%BF%99%E9%87%8C%E6%88%91%E4%BB%AC%E5%8F%AA%E5%BB%BA%E7%AB%8B%E6%9C%80%E7%AE%80%E5%8D%95%E7%9A%84%E5%A6%82%E4%B8%8B%EF%BC%9A%20...%205%205%EF%BC%8C%E5%88%9B%E5%BB%BA%E6%95%B0%E6%8D%AE%E6%9C%8D%E5%8A%A1%E5%B1%82-DAO%E5%B9%B6%E9%85%8D%E7%BD%AEMapper%20XML%20DAO%20%E5%B1%82%E4%B8%BB%E8%A6%81%E6%98%AFJava%E7%9A%84%E5%AF%B9%E4%BA%8E%E6%95%B0%E6%8D%AE%E5%BA%93%E6%93%8D%E4%BD%9C%E7%9A%84%E6%8E%A5%E5%8F%A3%E5%92%8C%E5%AE%9E%E7%8E%B0%E7%B1%BB%E3%80%82%20)

**Comment by smallcjy** [comment]
由于该模块和数据库接口关系紧密，故和 #5 一同开发
